### PR TITLE
[bugfix] unable to handle categorical column names with dots

### PR DESCRIPTION
**Pull request by gradientsky**
[nn.ModuleDict](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L388-L389) cannot handle `.` character in the column names.

### CODE REVIEW

**Comment by 5uperpalo** [comment]
thanks @Alex Z, I've been using a workaround, ie. doing this step in the data preprocessing(before using the library)... @Javier Rodriguez Zaurin looks good to me (maybe an additional warning saying that columns should not have "." in their name...)

**Comment by gradientsky** [comment]
Addressed formatting issues

**Comment by jrzaurin** [comment]
Hi @gradientsky 

So, in the latest release of torchmetrics they changed the name of the `F1` score to `F1score`

I am going to fix this in master. If you could fix it in your PR I will merge it afterwards

**Comment by gradientsky** [comment]
Rebased with master chages

**Pull request merged**
