### PR TITLE
Implement OneHotVector + Linear by Embedding

### PR DESCRIPTION
**Pull request by yuanzhiKe**
#18 I have tried to implement OneHotVector + Linear by Embedding layer.
It cost 1/130 memory and 10x faster on my own dataset, and the results are consistent.
I did not know what 'already_dummy' is for, thus I did nothing to it.
Just for your reference.

### CODE REVIEW

**Comment by javier-cazana** [comment]
Hey @yuanzhiKe THANKS!

I will have a look to the code, but is certainly an interesting approach. Thanks again for the contribution!

In the meantime, `already_dummy` is a list of columns that are previously one hot encoded, so there is not need to one hot encode them anymore, I will see how that fits in your implementation. 

Let me have a look to the code over the weekend. 

I have a question though. The fact that you use the term `vocab` is because you are using the wide component for text? or you intend this to be a general term?

**Comment by yuanzhiKe** [comment]
> Hey @yuanzhiKe THANKS!
> 
> I will have a look to the code, but is certainly an interesting approach. Thanks again for the contribution!
> 
> In the meantime, `already_dummy` is a list of columns that are previously one hot encoded, so there is not need to one hot encode them anymore, I will see how that fits in your implementation.
> 
> Let me have a look to the code over the weekend.
> 
> I have a question though. The fact that you use the term `vocab` is because you are using the wide component for text? or you intend this to be a general term?

I did not use it for text data. I used "vocab" as a general term. Since I saved categorical feature values of different columns in one dictionary by converting them to "<column_name>_<str(feature)>", I think the dictionary is like a vocabulary of "<column_name>_<str(feature)>".

**Comment by jrzaurin** [comment]
Hey @yuanzhiKe 

I was just asking, but thanks :) 

I will review your code and unit test it in the next few days

**Comment by jrzaurin** [comment]
Hey @yuanzhiKe 

going to close this, open a branch called `wide_embeddings` and open a PR for you to review.

**Pull request closed without merging**
